filter:
    excluded_paths: [vendor/*, app/*, web/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    external_code_coverage: true

checks:
    php:
        code_rating: true
        duplication: true
