---
- name: Deploy example app to my-server.com
  hosts: all
  become: root
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}" # Where my local project is (relative or absolute path)
    ansistrano_deploy_to: "/var/www/my-app"
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:mashware/SoapBundle.git
    ansistrano_git_branch: master

  # Variables used in the download deployment strategy
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }